# -*- coding: utf-8 -*-
"""Stable_LM_3B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1leMEJd8zAz-miCBCLoCszQL7LdAcVBq5
"""

!pip install datasets huggingface_hub transformers -qq

!pip install peft evaluate -qq

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Stable_LM_hackathon/model

from datasets import load_dataset, DatasetDict, Dataset, DatasetInfo
from peft import PeftModel, PeftConfig, get_peft_model, LoraConfig
import evaluate
import torch
import numpy as np

from transformers import (
    AutoTokenizer,
    AutoConfig,
    AutoModelForSequenceClassification,
    DataCollatorWithPadding,
    TrainingArguments,
    Trainer
)

# Datasets
# alan-23/HealthAssistant115
# jayashri710/mental-health-dataset
# health360/Healix-V1
# heliosbrahma/mental_health_conversational_dataset
# TheoTsio/Health_Misinfo
# alexandreteles/mental-health-conversational-data
# wangrongsheng/HealthCareMagic-100k-en
# rohanbalkondekar/HealthCareFacts_Small
# rppadmakumar/HealthBot
# RafaelMPereira/HealthCareMagic-100k-Chat-Format-en

model = "stabilityai/stablelm-3b-4e1t"

from huggingface_hub import notebook_login
notebook_login()

from huggingface_hub import snapshot_download

snapshot_download(repo_id="stabilityai/stablelm-3b-4e1t", local_dir="/content/drive/MyDrive/Stable_LM_hackathon/model")

